# Generated by Django 2.1.7 on 2021-01-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='videos',
            new_name='resources',
        ),
        migrations.AddField(
            model_name='course',
            name='password',
            field=models.CharField(default='pass', max_length=12),
        ),
    ]
