# Generated by Django 2.1.7 on 2021-01-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210123_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='password',
        ),
    ]
